In [15]:
import numpy as np
import pandas as pd
import glob
import os


allmp = pd.read_csv("../../input_data/targets.csv")  
allmp=allmp.reset_index(drop=True)

directory = "../../input_data/poscar/feature_topo_compo/"
i =0
topo_feature = []
for file in glob.iglob(f'{directory}/*'):
    #print(file)
    filename =file.split('/')[-1]
    #print(filename)
    mpid = filename.split('_')[0]
    #print(mpid)
    Ftopo = np.load(file)
    #print(len(Ftopo))

    entry = [mpid] + list(Ftopo)
    
    
    topo_feature.append(entry)
    
    if i%10000 ==0:
        df = pd.DataFrame(topo_feature)
        print(df.shape)
        df.to_csv('tmp_topo_test.csv',index=False)
        #break
    i = i+1
    #os.system(f"python cif2vasp.py {filename}")
df = pd.DataFrame(topo_feature)
#print(df.head)
df.to_csv('topo_feature.csv',index=False)

(1, 1246)

In [16]:
df

,0,1,2,3,4,5,6,7,8,9,...,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315
0,mp-191,23.369361,95.905675,3793.000000,6.000000,166.000000,8461.000000,15.650000,69.650000,1.750000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mp-177,25.470135,179.894455,3030.000000,9.000000,167.500000,12873.500000,15.750000,51.600000,1.715000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mp-189,16.792126,64.577750,3798.000000,11.000000,128.500000,7350.000000,7.565000,117.450000,2.050000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mp-171,11.667188,56.755425,3309.500000,8.750000,131.250000,8208.500000,8.200000,96.650000,1.840000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mp-178,24.730054,129.509799,3942.500000,8.000000,163.500000,7212.000000,19.450000,21.250000,1.455000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,mp-196,14.994835,36.110583,2908.571429,11.857143,122.428571,4471.428571,7.000000,48.557143,1.687143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,mp-186,22.893704,27.330577,2874.185185,12.074074,119.148148,2128.222222,8.282593,121.629630,1.756296,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,mp-183,28.182263,126.263500,2336.500000,7.500000,174.000000,7669.500000,18.460000,25.000000,1.405000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,mp-182,31.514719,75.688667,2203.000000,9.333333,146.333333,4812.666667,13.930000,20.943333,1.523333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,mp-201,38.659079,153.818750,1615.625000,7.500000,169.000000,6617.625000,15.537500,69.950000,1.556250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,mp-173,15.968465,30.975325,2726.571429,12.142857,123.571429,3381.428571,7.171429,36.428571,1.601429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,mp-170,26.360203,138.670660,2006.500000,7.500000,168.000000,8722.500000,15.460000,25.000000,1.460000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,mp-174,30.634306,175.589562,1564.125000,14.125000,142.375000,9746.250000,6.781250,83.325000,1.800000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,mp-181,33.669851,62.066825,2115.750000,10.000000,142.250000,4642.000000,16.897500,33.775000,1.562500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,mp-195,19.305443,187.545580,3816.750000,8.250000,150.000000,18016.250000,10.775000,166.475000,2.017500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,mp-193,19.453943,81.998000,4188.000000,6.333333,160.666667,7314.000000,13.983333,66.866667,1.520000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,mp-179,24.109448,77.142925,2399.000000,7.500000,156.000000,5806.000000,8.441667,14.800000,1.435000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,mp-172,29.054353,112.418889,3248.555556,7.888889,165.000000,6260.222222,20.040000,80.666667,1.526667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,mp-200,29.378687,44.465226,951.437500,13.500000,119.500000,2363.375000,7.063750,69.000000,2.053750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,mp-188,15.668954,153.058385,3771.500000,10.750000,132.250000,16492.500000,6.575000,164.600000,2.112500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,mp-190,13947.825458,58.551300,1534.825000,13.750000,87.250000,5256.071750,3.026500,109.375000,3.055000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
allmp_feat = pd.read_csv("../../../phase5/original_features/mp_130k_topo_feature.csv")

In [28]:
allmp_feat.head

<bound method NDFrame.head of                  0             1          2            3          4  \
0          mp-7984  13962.435371  42.914840   853.285000  13.875000
1         mp-15509   8152.616953  59.786113   937.866250  12.500000
2       mp-1215779     15.088615  74.850769  1654.461538  11.538462
3        mp-757942  10632.784019  22.943680   816.414286  12.857143
4        mp-764743  11164.125712  20.480918   713.685000  12.550000
...            ...           ...        ...          ...        ...
136015   mp-632229   9330.289883  40.455970   176.065000   9.000000
136016   mp-557228  12411.714257  48.752282   414.800000  14.740741
136017  mp-1227724  11165.975592  37.047969   876.260000  12.050000
136018  mp-1222836  10631.915722  30.248171  1059.485714  11.785714
136019  mp-1173221  10027.085742  50.784419  1075.515385  11.807692

                 5            6         7           8         9  ...  3231  \
0        86.125000  2932.022000  6.884000  265.312500  3.362500  ...   0.0
1       109.187500  2301.875188  6.810875  128.387500  2.541250  ...   0.0
2       125.923077  8266.846154 -3.366667   12.392308  1.776923  ...   0.0
3        89.000000  1610.245143  5.424714  115.371429  2.691429  ...   0.0
4        89.800000   999.557400  5.840950  108.135000  2.700500  ...   0.0
...            ...          ...       ...         ...       ...  ...   ...
136015   75.500000  1560.044950  1.858397  198.700000  2.580000  ...   0.0
136016   96.888889  1592.952667  5.626889  165.737037  3.025185  ...   0.0
136017  101.200000  2216.357400  6.241200   89.515500  2.625000  ...   0.0
136018   95.214286  2138.030857  6.663286  106.764286  2.620000  ...   0.0
136019  110.576923  2788.846385  7.847679   97.183077  2.519615  ...   0.0

        3232  3233  3234  3235  3236  3237  3238  3239  3240
0        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
...      ...   ...   ...   ...   ...   ...   ...   ...   ...
136015   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
136016   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
136017   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
136018   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
136019   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[136020 rows x 3241 columns]>

In [31]:
test20 = df.loc[df[0] == 'mp-186']
testmp = allmp_feat.loc[allmp_feat['0'] == 'mp-186']

In [32]:
print(test20)
print("=====================================")
print(testmp)

     0          1          2            3          4           5     \
6  mp-186  22.893704  27.330577  2874.185185  12.074074  119.148148

          6         7          8         9     ...  1306  1307  1308  1309  \
6  2128.222222  8.282593  121.62963  1.756296  ...   NaN   NaN   NaN   NaN

   1310  1311  1312  1313  1314  1315
6   NaN   NaN   NaN   NaN   NaN   NaN

[1 rows x 1316 columns]
=====================================
             0          1          2            3          4           5  \
116870  mp-186  22.893704  27.330577  2874.185185  12.074074  119.148148

                  6         7          8         9  ...  3231  3232  3233  \
116870  2128.222222  8.282593  121.62963  1.756296  ...   0.0   0.0   0.0

        3234  3235  3236  3237  3238  3239  3240
116870   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[1 rows x 3241 columns]